apiVersion: apim.wso2.com/v1alpha1
kind: APIManager
metadata:
  name: cluster-1
spec:
  pattern: Pattern-x
  profiles:
    custom:
      - name: new-api-manager
        type: api-manager
        deployment:
          replicas: 1
          minReadySeconds: 240
          imagePullPolicy: Always
          resources:
            requests:
              memory: 2Gi
              cpu: 2000m
            limits:
              memory: 3Gi
              cpu: 3000m
          livenessProbe:
            initialDelaySeconds: 180
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            initialDelaySeconds: 180
            failureThreshold: 3
            periodSeconds: 10
          configMaps:
            newConfigMap:
              - name: custom-sequence-new
                mountPath: /home/wso2carbon/wso2am-3.0.0-config/repository/resources/custom-sequences/new
          persistentVolumeClaim:
            newClaim:
              - name: new-pvc-claim-1
                mountPath: /home/wso2carbon/wso2-artifact-volume/repository/deployment/server/new


#     api-manager-1:
#       deployment:
#         replicas: 1
#         minReadySeconds: 240
#         imagePullPolicy: Always
#         resources:
#           requests:
#             memory: 2Gi
#             cpu: 2000m
#           limits:
#             memory: 3Gi
#             cpu: 3000m
#         livenessProbe:
#           initialDelaySeconds: 180
#           failureThreshold: 3
#           periodSeconds: 10
#         readinessProbe:
#           initialDelaySeconds: 180
#           failureThreshold: 3
#           periodSeconds: 10
#        configMaps:
#          deploymentConfigMap: wso2am-p1-apim-1-conf
#          newConfigMap:
#            - name: custom-sequence-in-cm
#              mountPath: /home/wso2carbon/wso2am-3.0.0-config/repository/resources/custom-sequences/in
#            - name: custom-sequence-out-cm
#              mountPath: /home/wso2carbon/wso2am-3.0.0-config/repository/resources/custom-sequences/
#        persistentVolumeClaim:
#          synapseConfigs: custom-synapse-config
#          executionPlans: custom-execution-plan
#          newClaim:
#            - name: new-pvc-claim-1
#              mountPath: /home/wso2carbon/wso2-artifact-volume/repository/deployment/server/vol1
#            - name: new-pvc-claim-2
#              mountPath: /home/wso2carbon/wso2-artifact-volume/repository/deployment/server/vol2

#
#    api-manager-2:
#      deployment:
#        resources:
#          requests:
#            memory: 2Gi
#            cpu: 2000m
#          limits:
#            memory: 3Gi
#            cpu: 3000m
#        replicas: 1
#        minReadySeconds: 240
#        imagePullPolicy: Always
#        livenessProbe:
#          initialDelaySeconds: 240
#          failureThreshold: 3
#          periodSeconds: 10
#        readinessProbe:
#          initialDelaySeconds: 240
#          failureThreshold: 3
#          periodSeconds: 10
#
#
#    analytics-dashboard:
#      deployment:
#        resources:
#          requests:
#            memory: 4Gi
#            cpu: 2000m
#          limits:
#            memory: 4Gi
#            cpu: 2000m
#        replicas: 1
#        minReadySeconds: 30
#        imagePullPolicy: Always
#        livenessProbe:
#          initialDelaySeconds: 20
#          failureThreshold: 3
#          periodSeconds: 10
#        readinessProbe:
#          initialDelaySeconds: 20
#          failureThreshold: 3
#          periodSeconds: 10
#
#    analytics-worker:
#      deployment:
#        resources:
#          requests:
#            memory: 4Gi
#            cpu: 2000m
#          limits:
#            memory: 4Gi
#            cpu: 2000m
#        replicas: 1
#        minReadySeconds: 30
#        imagePullPolicy: Always
#        livenessProbe:
#          initialDelaySeconds: 20
#          failureThreshold: 3
#          periodSeconds: 10
#        readinessProbe:
#          initialDelaySeconds: 20
#          failureThreshold: 3
#          periodSeconds: 10
