apiVersion: apim.wso2.com/v1alpha1
kind: APIManager
metadata:
  name: cluster-1
spec:
  pattern: Pattern-1
  service:
    type: NodePort
  profiles:
    api-manager-1:
      configMaps:
        deploymentConfigMap: wso2am-p1-apim-1-conf
    api-manager-2:
      configMaps:
        deploymentConfigMap: wso2am-p1-apim-2-conf
