apiVersion: apim.wso2.com/v1alpha1
kind: APIManager
metadata:
  name: cluster-1
spec:
  pattern: Pattern-1
  service:
    type: NodePort
  profiles:
    - name: api-manager-1
      deployment:
        configMaps:
          deploymentConfigMap: wso2am-p1-apim-1-conf-cluster-1

    - name: api-manager-1
      deployment:
        configMaps:
          deploymentConfigMap: wso2am-p1-apim-2-conf-cluster-1
