apiVersion: apim.wso2.com/v1alpha1
kind: APIManager
metadata:
  name: cluster-1
spec:
  pattern: Pattern-1
  service:
    type: NodePort
  profiles:
    - name: api-manager-1
      deployment:
        configMaps:
          deploymentConfigMap: my-nodeport-conf-1
#
    - name: api-manager-2
      deployment:
        configMaps:
          deploymentConfigMap: my-nodeport-conf-2

    - name: analytics-dashboard
      deployment:
        configMaps:
          deploymentConfigMap: my-dash-conf
