apiVersion: apim.wso2.com/v1alpha1
kind: APIManager
metadata:
  name: cluster-1
spec:
  pattern: Pattern-1
  service:
    type: NodePort
  profiles:
    api-manager-1:
      configMaps:
        deploymentConfigMap: wso2am-pattern-1-am-1-conf
