apiVersion: apim.wso2.com/v1alpha1
kind: APIManager
metadata:
  name: cluster-1
spec:
  pattern: Pattern-X
  service:
    type: NodePort
  profiles:
    - name: my-api-manager-1
      type: api-manager
      service:
        name: my-api-manager-svc-1
      deployment:
        replicas: 1
        minReadySeconds: 100
        imagePullPolicy: Always
        resources:
          requests:
            memory: 2Gi
            cpu: 2000m
          limits:
            memory: 3Gi
            cpu: 3000m
        livenessProbe:
          initialDelaySeconds: 240
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          initialDelaySeconds: 240
          failureThreshold: 3
          periodSeconds: 10
        configMaps:
          deploymentConfigMap: my-api-manager-1-conf

    - name: my-api-manager-2
      type: api-manager
      service:
        name: my-api-manager-svc-2
      deployment:
        replicas: 1
        minReadySeconds: 100
        imagePullPolicy: Always
        resources:
          requests:
            memory: 2Gi
            cpu: 2000m
          limits:
            memory: 3Gi
            cpu: 3000m
        livenessProbe:
          initialDelaySeconds: 240
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          initialDelaySeconds: 240
          failureThreshold: 3
          periodSeconds: 10
        configMaps:
          deploymentConfigMap: my-api-manager-2-conf

    - name: my-analy-dash-1
      type: analytics-dashboard
      service:
        name: my-analy-dash-svc
      deployment:
        replicas: 1
        minReadySeconds: 100
        imagePullPolicy: Always
        resources:
          requests:
            memory: 2Gi
            cpu: 2000m
          limits:
            memory: 3Gi
            cpu: 3000m
        livenessProbe:
          initialDelaySeconds: 240
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          initialDelaySeconds: 240
          failureThreshold: 3
          periodSeconds: 10
        configMaps:
          deploymentConfigMap: my-dash-conf


    - name: my-analy-worker-1
      type: analytics-worker
      service:
        name: my-analy-worker-svc
      deployment:
        replicas: 1
        minReadySeconds: 100
        imagePullPolicy: Always
        resources:
          requests:
            memory: 2Gi
            cpu: 2000m
          limits:
            memory: 3Gi
            cpu: 3000m
        livenessProbe:
          initialDelaySeconds: 240
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          initialDelaySeconds: 240
          failureThreshold: 3
          periodSeconds: 10
        configMaps:
          deploymentConfigMap: my-worker-conf










#    - name: analytics-new
#      type: analytics
#      deployment:
#        replicas: 1
#        minReadySeconds: 100
#        imagePullPolicy: Always
#        resources:
#          requests:
#            memory: 2Gi
#            cpu: 2000m
#          limits:
#            memory: 3Gi
#            cpu: 3000m
#        livenessProbe:
#          initialDelaySeconds: 60
#          failureThreshold: 3
#          periodSeconds: 10
#        readinessProbe:
#          initialDelaySeconds: 60
#          failureThreshold: 3
#          periodSeconds: 10

#        configMaps:
#          deploymentConfigMap: wso2am-p1-apim-1-conf-new
#          newConfigMap:
#            - name: custom-sequence-in-cm
#              mountPath: /home/wso2carbon/wso2am-3.0.0-config/repository/resources/custom-sequences/in
#            - name: custom-sequence-out-cm
#              mountPath: /home/wso2carbon/wso2am-3.0.0-config/repository/resources/custom-sequences/
#        persistentVolumeClaim:
#          synapseConfigs: custom-synapse-config-new
#          executionPlans: custom-execution-plan-new
#          newClaim:
#            - name: new-pvc-claim-1
#              mountPath: /home/wso2carbon/wso2-artifact-volume/repository/deployment/server/vol1
#            - name: new-pvc-claim-2
#              mountPath: /home/wso2carbon/wso2-artifact-volume/repository/deployment/server/vol2


#    - name: api-manager-1
#      deployment:
#        replicas: 1
#        minReadySeconds: 240
#        imagePullPolicy: Always
#        resources:
#          requests:
#            memory: 2Gi
#            cpu: 2000m
#          limits:
#            memory: 3Gi
#            cpu: 3000m
#        livenessProbe:
#          initialDelaySeconds: 180
#          failureThreshold: 3
#          periodSeconds: 10
#        readinessProbe:
#          initialDelaySeconds: 180
#          failureThreshold: 3
#          periodSeconds: 10

#        configMaps:
#          deploymentConfigMap: wso2am-p1-apim-1-conf
#          newConfigMap:
#            - name: custom-sequence-in-cm
#              mountPath: /home/wso2carbon/wso2am-3.0.0-config/repository/resources/custom-sequences/in
#            - name: custom-sequence-out-cm
#              mountPath: /home/wso2carbon/wso2am-3.0.0-config/repository/resources/custom-sequences/
#        persistentVolumeClaim:
#          synapseConfigs: custom-synapse-config
#          executionPlans: custom-execution-plan
#          newClaim:
#            - name: new-pvc-claim-1
#              mountPath: /home/wso2carbon/wso2-artifact-volume/repository/deployment/server/vol1
#            - name: new-pvc-claim-2
#              mountPath: /home/wso2carbon/wso2-artifact-volume/repository/deployment/server/vol2
#
