apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-execution-plans
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/docker/my-test/my-execution"