apiVersion: v1
kind: Service
metadata:
  name: wso2apim-mysql-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    deployment: wso2apim-mysql
  ports:
    - name: mysql-port
      port: 3306
      targetPort: 3306
      protocol: TCP