apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wso2am-controller-role
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
      - secrets
      - events
      - services
      - serviceaccounts
      - configmaps
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups:
      - apim.wso2.com
    resources:
      - apimanagers
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
