apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: wso2am-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wso2am-controller-role
subjects:
  - kind: ServiceAccount
    name: wso2am-pattern-1-svc-account
    namespace: wso2-system