apiVersion: apim.wso2.com/v1alpha1
kind: APIManager
metadata:
  name: cluster-1
spec:
  pattern: Pattern-1
  profiles:
    - name: api-manager-1
      deployment:
        configMaps:
          newConfigMap:
            - name: <NEW_CONFIGMAP_1>
              mountPath: <NEW_MOUNTPATH_FOR_CONFIGMAP_1>
        persistentVolumeClaim:
          newClaim:
            - name: <NEW_CLAIM_1>
              mountPath: <NEW_MOUNTPATH_FOR_CLAIM_1>
