apiVersion: v1
kind: PersistentVolume
metadata:
  name: wso2am-p1-apim-synapse-configs-pv
  labels:
    name: wso2am-p1-apim-synapse-configs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "NAME_SPACE"
    name: wso2am-p1-am-synapse-configs
  storageClassName: "STORAGE_CLASS_NAME"
  nfs:
    path: "NFS_LOCATION_PATH"
    server: "NFS_SERVER_IP"
 
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: wso2am-p1-apim-execution-plans-pv
  labels:
    name: wso2am-p1-apim-execution-plans
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "NAME_SPACE"
    name: wso2am-p1-am-execution-plans
  storageClassName: "STORAGE_CLASS_NAME"
  nfs:
    path: "NFS_LOCATION_PATH"
    server: "NFS_SERVER_IP"
 
---
 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wso2am-p1-mysql-pv
  labels:
    name: wso2am-p1-apim-mysql
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "NAME_SPACE"
    name: wso2am-p1-mysql
  storageClassName: "STORAGE_CLASS_NAME"
  nfs:
    path: "NFS_LOCATION_PATH"
    server: "NFS_SERVER_IP"
