apiVersion: v1
kind: PersistentVolume
metadata:
  name: wso2am-p1-apim-synapse-configs-pv
  labels:
    name: wso2am-p1-apim-synapse-configs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: test
    name: wso2am-p1-am-synapse-configs
  storageClassName: new
  nfs:
    path: /test/wso2-apim/pattern-1/synapse-configs
    server: 192.168.114.18
 
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: wso2am-p1-apim-execution-plans-pv
  labels:
    name: wso2am-p1-apim-execution-plans
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: test
    name: wso2am-p1-am-execution-plans
  storageClassName: new
  nfs:
    path: /test/wso2-apim/pattern-1/executionplans
    server: 192.168.114.18
 
---
 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wso2am-p1-mysql-pv
  labels:
    name: wso2am-p1-apim-mysql
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: test
    name: wso2am-p1-mysql
  storageClassName: new
  nfs:
    path: /test/wso2-apim/pattern-1/mysql
    server: 192.168.114.18