apiVersion: v1
kind: PersistentVolume
metadata:
  name: wso2am-p1-am-synapse-configs
  namespace: test
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/docker/test/synapse"