apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2am-p1-mysql
  namespace: test2
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
#   selector:
#     matchLabels:
#       name: apim-mysql
