apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2am-p1-am-execution-plans
  namespace: test2
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi