apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
#  labels:
#    name: apim-rdbms-data
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/my-test/my-mysql"