apiVersion: apim.wso2.com/v1alpha1
kind: APIManager
metadata:
  name: cluster-1
spec:
  pattern: Pattern-1
  service:
    type: ClusterIP
  profiles:
    - name: api-manager-1
      deployment:
        configMaps:
          deploymentConfigMap: mydeploy1
    - name: api-manager-2
      deployment:
        configMaps:
          deploymentConfigMap: mydeploy2
    - name: analytics-dashboard
      deployment:
        configMaps:
          deploymentConfigMap: mydash