apiVersion: apim.wso2.com/v1alpha1
kind: APIManager
metadata:
  name: cluster-1
  namespace: keshi2
spec:
  pattern: Pattern-1
  profiles:
    api-manager-1:
      apim-deployment:
        resources:
          requests:
            memory: 2Gi
            cpu: 2000m
          limits:
            memory: 3Gi
            cpu: 3000m
        image: wso2/wso2am:3.0.0
      deployment:
        replicas: 1
        minReadySeconds: 240
        strategy:
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 240
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          initialDelaySeconds: 240
          failureThreshold: 3
          periodSeconds: 10
      deployment-configmap: new-deployment-toml-1
#      persistent-volume-claim-server: new-claim
    api-manager-2:
      deployment-configmap: new-deployment-toml-2



