apiVersion: apim.wso2.com/v1alpha1
kind: APIManager
metadata:
  name: cluster-1
  namespace: keshi2
spec:
  pattern: Pattern-1
  profiles:
    #configuratiosn for apim instance 1
    - name: api-manager1
      resources:
        requests:
          memory: 2Gi
          cpu: 2000m
          limits:
            memory: 3Gi
            cpu: 3000m
      replicas: 1
      minReadySeconds: 240
      strategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      imagePullPolicy: Always
      livenessProbe:
        initialDelaySeconds: 240
        failureThreshold: 3
        periodSeconds: 10
      readinessProbe:
        initialDelaySeconds: 240
        failureThreshold: 3
        periodSeconds: 10
      deploymentConfigmap: new-deployment-toml-1
      persistentVolumeClaimServer:
        synapseConfigs: new-claim-1
        executionPlans: new-claim-2

      #configuratiosn for apim instance 2
    - name: api-manager2
      resources:
        requests:
          memory: 2Gi
          cpu: 2000m
        limits:
          memory: 3Gi
          cpu: 3000m
      replicas: 1
      minReadySeconds: 240
      strategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      imagePullPolicy: Always
      livenessProbe:
        initialDelaySeconds: 240
        failureThreshold: 3
        periodSeconds: 10
      readinessProbe:
        initialDelaySeconds: 240
        failureThreshold: 3
        periodSeconds: 10
      deploymentConfigmap: new-deployment-toml-2

      #configurations for analytics dashboard
    - name: analytics-dashboard
      resources:
        requests:
          memory: 4Gi
          cpu: 2000m
        limits:
          memory: 4Gi
          cpu: 2000m
      replicas: 1
      minReadySeconds: 30
      strategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      imagePullPolicy: Always
      livenessProbe:
        initialDelaySeconds: 20
        failureThreshold: 3
        periodSeconds: 10
      readinessProbe:
        initialDelaySeconds: 20
        failureThreshold: 3
        periodSeconds: 10
      deploymentConfigmap: new-dashboard-toml


    #configurations for analytics worker
    - name: analytics-worker
      resources:
        requests:
          memory: 4Gi
          cpu: 2000m
        limits:
          memory: 4Gi
          cpu: 2000m
      replicas: 1
      minReadySeconds: 30
      strategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      imagePullPolicy: Always
      livenessProbe:
        initialDelaySeconds: 20
        failureThreshold: 3
        periodSeconds: 10
      readinessProbe:
        initialDelaySeconds: 20
        failureThreshold: 3
        periodSeconds: 10
      deploymentConfigmap: new-worker-toml








