apiVersion: apim.wso2.com/v1alpha1
kind: APIManager
metadata:
  name: cluster-1
  namespace: test
spec:
  pattern: Pattern-1
  service:
    type: NodePort
  profiles:
    #configuratiosn for apim instance 1
    - name: api-manager-1
      deployment:
        resources:
          requests:
            memory: 2Gi
            cpu: 2000m
          limits:
            memory: 3Gi
            cpu: 3000m
        replicas: 1
        minReadySeconds: 240
        strategy:
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 240
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          initialDelaySeconds: 240
          failureThreshold: 3
          periodSeconds: 10
        configmaps:
          deploymentConfigmap: wso2am-pattern-1-am-1-conf
#          newConfigmap:
#            - name: custom-sequence-in-cm
#              mountPath: /home/wso2carbon/wso2am-3.0.0-config/repository/resources/custom-sequences/in
#            - name: custom-sequence-out-cm
#              mountPath: /home/wso2carbon/wso2am-3.0.0-config/repository/resources/custom-sequences/
#        persistentVolumeClaim:
#          synapseConfig:
#          executionPlans:
#          newClaim:

      #configuratiosn for apim instance 2
    - name: api-manager-2
      service:
        type: NodePort
      deployment:
        resources:
          requests:
            memory: 2Gi
            cpu: 2000m
          limits:
            memory: 3Gi
            cpu: 3000m
        replicas: 1
        minReadySeconds: 240
        strategy:
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 240
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          initialDelaySeconds: 240
          failureThreshold: 3
          periodSeconds: 10

      #configurations for analytics dashboard
    - name: analytics-dashboard
      service:
        type: NodePort
      deployment:
        resources:
          requests:
            memory: 4Gi
            cpu: 2000m
          limits:
            memory: 4Gi
            cpu: 2000m
        replicas: 1
        minReadySeconds: 30
        strategy:
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 20
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          initialDelaySeconds: 20
          failureThreshold: 3
          periodSeconds: 10

    #configurations for analytics worker
    - name: analytics-worker
      service:
        type: NodePort
      deployment:
        resources:
          requests:
            memory: 4Gi
            cpu: 2000m
          limits:
            memory: 4Gi
            cpu: 2000m
        replicas: 1
        minReadySeconds: 30
        strategy:
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 20
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          initialDelaySeconds: 20
          failureThreshold: 3
          periodSeconds: 10


